#!/usr/bin/env python3
"""
AGENT 1 — Procedural asset synthesizer for the Godot 4 hack-and-slash game.
No network. Everything is synthesized with numpy/PIL. Deterministic (seeded RNG).
License-clean: all content generated by this script.

Outputs:
  ~/workspace/horror-game/assets/audio/*.wav      (44100 Hz, 16-bit mono)
  ~/workspace/horror-game/assets/textures/*.png   (512x512 seamless)
"""
import os
import wave
import numpy as np
from PIL import Image, ImageDraw

SEED = 20260925
SR = 44100
SIZE = 512  # texture resolution

ROOT = os.path.expanduser("~/workspace/horror-game")
AUDIO_DIR = os.path.join(ROOT, "assets", "audio")
TEX_DIR = os.path.join(ROOT, "assets", "textures")
os.makedirs(AUDIO_DIR, exist_ok=True)
os.makedirs(TEX_DIR, exist_ok=True)

rng = np.random.default_rng(SEED)

# ---------------------------------------------------------------- audio utils
def t_of(dur):
    return np.arange(int(SR * dur), dtype=np.float64) / SR

def fade(sig, ms=8.0):
    n = int(SR * ms / 1000.0)
    n = max(2, min(n, len(sig) // 4))
    w = 0.5 * (1.0 - np.cos(np.pi * np.arange(n) / n))
    sig = sig.astype(np.float64).copy()
    sig[:n] *= w
    sig[-n:] *= w[::-1]
    return sig

def peak_normalize(sig, dbfs=-3.0):
    peak = float(np.max(np.abs(sig))) if sig.size else 0.0
    target = 10.0 ** (dbfs / 20.0)
    return sig * (target / peak) if peak > 1e-9 else sig

def write_wav(path, sig):
    sig = peak_normalize(fade(sig))  # fade first (no clicks), then normalize
    pcm = (np.clip(sig, -1.0, 1.0) * 32767.0).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())
    return len(pcm) / SR

def exp_decay(dur, tau, delay=0.0):
    t = t_of(dur)
    e = np.exp(-np.maximum(0.0, t - delay) / tau)
    e[t < delay] = 0.0
    return e

def attack_env(dur, attack, decay_tau):
    t = t_of(dur)
    a = np.clip(t / max(attack, 1e-4), 0.0, 1.0)
    a = a * a * (3.0 - 2.0 * a)  # smoothstep attack
    return a * np.exp(-t / decay_tau)

def glide_tone(dur, f0, f1, kind="sine", phase0=0.0):
    """Sine/sawtooth with exponential frequency glide f0 -> f1."""
    t = t_of(dur)
    if abs(f1 - f0) < 1e-9:
        phase = 2.0 * np.pi * f0 * t + phase0
    else:
        k = np.log(f1 / f0) / dur
        phase = 2.0 * np.pi * f0 * (np.exp(k * t) - 1.0) / k + phase0
    cyc = phase / (2.0 * np.pi)
    if kind == "sine":
        return np.sin(phase)
    return 2.0 * (cyc - np.floor(cyc)) - 1.0  # sawtooth

def butterworth_mag(n_fft, cutoff, order, highpass=False):
    f = np.fft.rfftfreq(n_fft, 1.0 / SR)
    m = 1.0 / np.sqrt(1.0 + (f / max(cutoff, 1e-3)) ** (2 * order))
    return m if not highpass else (1.0 - m)

def spectral_filter(x, cutoff, order=2, highpass=False):
    n = 1
    while n < len(x):
        n *= 2
    X = np.fft.rfft(x, n)
    H = butterworth_mag(n, cutoff, order, highpass)
    return np.fft.irfft(X * H, n)[: len(x)]

def swept_noise(dur, f0, f1, bw, env=None, n_fft=2048, hop=512):
    """Band-passed white noise with center frequency sweeping f0 -> f1."""
    n = int(SR * dur)
    x = rng.standard_normal(n)
    win = np.hanning(n_fft)
    freqs = np.fft.rfftfreq(n_fft, 1.0 / SR)
    out = np.zeros(n + n_fft)
    pos = 0
    while pos < n:
        seg = x[pos:pos + n_fft]
        if len(seg) < n_fft:
            seg = np.pad(seg, (0, n_fft - len(seg)))
        fc = f0 + (f1 - f0) * (pos / n)
        H = np.exp(-0.5 * ((freqs - fc) / bw) ** 2)
        y = np.fft.irfft(np.fft.rfft(seg * win) * H, n_fft)
        out[pos:pos + n_fft] += y * win
        pos += hop
    out = out[:n]
    if env is not None:
        out = out * env
    return out

def struck_partials(dur, base, ratios, amps, taus):
    t = t_of(dur)
    y = np.zeros_like(t)
    for r, a, tau in zip(ratios, amps, taus):
        y += a * np.sin(2.0 * np.pi * base * r * t + rng.uniform(0, 2 * np.pi)) * np.exp(-t / tau)
    return y

# ------------------------------------------------------------------- SFX set
def sfx_swing_light():
    dur = 0.25
    env = attack_env(dur, 0.03, 0.07)
    return swept_noise(dur, 1200.0, 4500.0, 700.0, env)

def sfx_swing_heavy():
    dur = 0.45
    env = attack_env(dur, 0.05, 0.13)
    body = swept_noise(dur, 350.0, 1400.0, 500.0, env)
    rumble = spectral_filter(rng.standard_normal(int(SR * dur)), 180.0, order=3)
    rumble *= attack_env(dur, 0.06, 0.16) * 0.8
    tail = swept_noise(dur, 1400.0, 700.0, 400.0, exp_decay(dur, 0.20) * 0.4)
    return body + rumble + tail

def sfx_flesh_slice():
    dur = 0.30
    env = attack_env(dur, 0.008, 0.06)
    squelch = swept_noise(dur, 3200.0, 500.0, 900.0, env)
    wet = spectral_filter(rng.standard_normal(int(SR * dur)), 900.0, order=2)
    wet *= attack_env(dur, 0.01, 0.09) * 0.7
    tone = glide_tone(dur, 800.0, 200.0) * exp_decay(dur, 0.05) * 0.25
    return squelch + wet + tone

def sfx_blood_impact():
    dur = 0.35
    thud = glide_tone(dur, 100.0, 50.0) * exp_decay(dur, 0.09)
    splat = swept_noise(dur, 2500.0, 900.0, 800.0, attack_env(dur, 0.005, 0.07)) * 0.8
    drip = spectral_filter(rng.standard_normal(int(SR * dur)), 400.0, order=2)
    drip *= exp_decay(dur, 0.16, delay=0.05) * 0.35
    return thud + splat + drip

def sfx_stone_impact():
    dur = 0.50
    click = spectral_filter(rng.standard_normal(int(SR * dur)), 2500.0, order=2, highpass=True)
    click *= exp_decay(dur, 0.012) * 0.9
    crack = swept_noise(dur, 3200.0, 1500.0, 900.0, exp_decay(dur, 0.06)) * 0.7
    boom = glide_tone(dur, 75.0, 32.0) * exp_decay(dur, 0.22) * 1.0
    return click + crack + boom

def sfx_wood_impact():
    dur = 0.40
    knock = struck_partials(dur, 1.0, [185.0, 262.0, 341.0, 523.0],
                            [1.0, 0.6, 0.4, 0.2], [0.09, 0.07, 0.05, 0.03])
    hit = spectral_filter(rng.standard_normal(int(SR * dur)), 1200.0, order=2)
    hit *= exp_decay(dur, 0.02) * 0.6
    return knock + hit

def sfx_recall_whistle():
    dur = 0.80
    t = t_of(dur)
    vib = 25.0 * np.sin(2.0 * np.pi * 7.0 * t)
    # frequency glide with vibrato: integrate instantaneous frequency
    f0, f1 = 600.0, 1800.0
    k = np.log(f1 / f0) / dur
    base_phase = 2.0 * np.pi * f0 * (np.exp(k * t) - 1.0) / k
    vib_phase = np.cumsum(vib) / SR * 2.0 * np.pi
    tone = np.sin(base_phase + vib_phase)
    env = np.clip(t / 0.25, 0.0, 1.0) * np.clip((dur - t) / 0.25, 0.0, 1.0)
    airy = swept_noise(dur, 900.0, 2200.0, 500.0, env * 0.25)
    return tone * env + airy

def sfx_catch_metal():
    dur = 0.70
    ratios = [1.0, 1.51, 2.09, 2.94, 4.20]
    amps = [1.0, 0.55, 0.4, 0.28, 0.15]
    taus = [0.50, 0.35, 0.25, 0.18, 0.12]
    metal = struck_partials(dur, 196.0, ratios, amps, taus)
    tick = spectral_filter(rng.standard_normal(int(SR * dur)), 4000.0, order=2, highpass=True)
    tick *= exp_decay(dur, 0.008) * 0.5
    return metal + tick

def sfx_grunt_player():
    dur = 0.30
    g = glide_tone(dur, 170.0, 95.0, kind="saw")
    g = spectral_filter(g, 900.0, order=2)
    breath = spectral_filter(rng.standard_normal(int(SR * dur)), 600.0, order=2)
    env = attack_env(dur, 0.02, 0.08)
    return (g * 0.9 + breath * 0.4) * env

def sfx_roar_enemy():
    dur = 1.00
    t = t_of(dur)
    wob = 15.0 * np.sin(2.0 * np.pi * 5.0 * t)
    f_inst = 95.0 + wob
    phase = np.cumsum(f_inst) / SR * 2.0 * np.pi
    saw = 2.0 * ((phase / (2.0 * np.pi)) % 1.0) - 1.0
    saw = spectral_filter(saw, 700.0, order=3)
    am = 0.55 + 0.45 * np.sin(2.0 * np.pi * 27.0 * t)  # guttural amplitude modulation
    growl = saw * am
    noise = spectral_filter(rng.standard_normal(int(SR * dur)), 500.0, order=2) * 0.5
    sub = np.sin(2.0 * np.pi * 55.0 * t) * 0.4
    env = np.clip(t / 0.15, 0.0, 1.0) * np.clip((dur - t) / 0.35, 0.0, 1.0)
    return (growl + noise + sub) * env

def sfx_footstep_heavy():
    dur = 0.30
    thump = glide_tone(dur, 75.0, 38.0) * exp_decay(dur, 0.07)
    scuff = spectral_filter(rng.standard_normal(int(SR * dur)), 300.0, order=2)
    scuff *= attack_env(dur, 0.01, 0.05) * 0.5
    return thump + scuff

def sfx_embed_thunk():
    dur = 0.40
    wood = struck_partials(dur, 1.0, [210.0, 320.0, 470.0], [0.8, 0.5, 0.3], [0.12, 0.08, 0.05])
    metal = struck_partials(dur, 1.0, [890.0, 1560.0], [0.25, 0.15], [0.10, 0.06])
    thud = glide_tone(dur, 90.0, 50.0) * exp_decay(dur, 0.10) * 0.8
    return wood + metal + thud

SFX_JOBS = [
    ("swing_light.wav", 0.25, sfx_swing_light),
    ("swing_heavy.wav", 0.45, sfx_swing_heavy),
    ("flesh_slice.wav", 0.30, sfx_flesh_slice),
    ("blood_impact.wav", 0.35, sfx_blood_impact),
    ("stone_impact.wav", 0.50, sfx_stone_impact),
    ("wood_impact.wav", 0.40, sfx_wood_impact),
    ("recall_whistle.wav", 0.80, sfx_recall_whistle),
    ("catch_metal.wav", 0.70, sfx_catch_metal),
    ("grunt_player.wav", 0.30, sfx_grunt_player),
    ("roar_enemy.wav", 1.00, sfx_roar_enemy),
    ("footstep_heavy.wav", 0.30, sfx_footstep_heavy),
    ("embed_thunk.wav", 0.40, sfx_embed_thunk),
]

# ------------------------------------------------------------- texture utils
def periodic_value_noise(size, cells):
    lat = rng.random((cells, cells))
    t = np.linspace(0.0, cells, size, endpoint=False)
    fl = np.floor(t)
    i0 = fl.astype(np.int64) % cells
    f = t - fl
    s = f * f * (3.0 - 2.0 * f)
    i1 = (i0 + 1) % cells
    top = lat[:, i0] * (1.0 - s)[None, :] + lat[:, i1] * s[None, :]
    A = top[i0, :]
    B = top[i1, :]
    w = s[:, None]
    return A * (1.0 - w) + B * w

def fbm(size, base_cells, octaves):
    total = np.zeros((size, size))
    amp, freq, norm = 1.0, base_cells, 0.0
    for _ in range(octaves):
        total += amp * periodic_value_noise(size, freq)
        norm += amp
        amp *= 0.5
        freq *= 2
    return total / norm

def height_to_normal(h, strength=2.0):
    dx = (np.roll(h, -1, axis=1) - np.roll(h, 1, axis=1)) * 0.5 * strength
    dy = (np.roll(h, -1, axis=0) - np.roll(h, 1, axis=0)) * 0.5 * strength
    n = np.stack([-dx, -dy, np.ones_like(h)], axis=-1)
    n /= np.linalg.norm(n, axis=-1, keepdims=True) + 1e-9
    return ((n * 0.5 + 0.5) * 255.0).astype(np.uint8)

def save_rgb(path, arr):
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8), "RGB").save(path)

def save_gray(path, arr):
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8), "L").save(path)

# ------------------------------------------------------------------ textures
def tex_stone():
    s = SIZE
    base = fbm(s, 4, 5)
    detail = fbm(s, 16, 4)
    height = 0.65 * base + 0.35 * detail
    crack_field = fbm(s, 6, 4)
    cracks = np.clip(1.0 - np.abs(crack_field - 0.5) * 9.0, 0.0, 1.0)
    fine = np.clip(1.0 - np.abs(fbm(s, 24, 3) - 0.5) * 14.0, 0.0, 1.0)
    crack_all = np.clip(cracks + 0.6 * fine, 0.0, 1.0)
    moss_mask = np.clip((fbm(s, 3, 3) - 0.55) * 4.0, 0.0, 1.0) * np.clip((0.45 - height) * 4.0, 0.0, 1.0)
    gray = 0.42 + 0.16 * (base - 0.5) * 2.0 + 0.06 * (detail - 0.5) * 2.0
    gray = np.clip(gray - 0.28 * crack_all, 0.05, 1.0)
    r = gray * 255.0
    g = gray * 252.0
    b = gray * 244.0
    r = r * (1 - 0.25 * moss_mask) + 90.0 * moss_mask
    g = g * (1 - 0.15 * moss_mask) + 115.0 * moss_mask
    b = b * (1 - 0.35 * moss_mask) + 70.0 * moss_mask
    save_rgb(os.path.join(TEX_DIR, "stone_albedo.png"), np.stack([r, g, b], axis=-1))
    save_rgb(os.path.join(TEX_DIR, "stone_normal.png"),
             height_to_normal(height - 0.55 * crack_all, strength=2.5))
    rough = 200.0 + 35.0 * crack_all + 25.0 * moss_mask - 20.0 * (detail - 0.5)
    save_gray(os.path.join(TEX_DIR, "stone_roughness.png"), rough)

def tex_iron():
    s = SIZE
    # brushed: stretched noise (few cells vertically -> horizontal streaks)
    lat = rng.random((4, 96))
    ty = np.linspace(0.0, 4, s, endpoint=False)
    tx = np.linspace(0.0, 96, s, endpoint=False)
    fy = ty - np.floor(ty); sy = fy * fy * (3 - 2 * fy)
    fx = tx - np.floor(tx); sx = fx * fx * (3 - 2 * fx)
    iy0 = np.floor(ty).astype(int) % 4; iy1 = (iy0 + 1) % 4
    ix0 = np.floor(tx).astype(int) % 96; ix1 = (ix0 + 1) % 96
    a = lat[iy0][:, ix0] * (1 - sx)[None, :] + lat[iy0][:, ix1] * sx[None, :]
    b = lat[iy1][:, ix0] * (1 - sx)[None, :] + lat[iy1][:, ix1] * sx[None, :]
    streak = a * (1 - sy)[:, None] + b * sy[:, None]
    var = fbm(s, 4, 4)
    wear = np.clip((fbm(s, 3, 3) - 0.60) * 5.0, 0.0, 1.0)
    base = 0.16 + 0.035 * (streak - 0.5) * 2.0 + 0.03 * (var - 0.5) * 2.0
    base = np.clip(base + 0.06 * wear, 0.02, 1.0)
    r = base * 255.0
    g = (base * 1.04) * 255.0
    bch = (base * 1.18) * 255.0
    save_rgb(os.path.join(TEX_DIR, "iron_albedo.png"), np.stack([r, g, bch], axis=-1))
    rough = 150.0 + 45.0 * (streak - 0.5) * 2.0 - 50.0 * wear + 20.0 * (var - 0.5) * 2.0
    save_gray(os.path.join(TEX_DIR, "iron_roughness.png"), rough)

RUNES = [
    [((2, 0), (2, 6)), ((2, 1), (4, 0)), ((2, 2.5), (4, 1.5))],          # fehu
    [((1, 0), (1, 6)), ((1, 0), (3, 2)), ((3, 2), (3, 6))],              # uruz
    [((2, 0), (2, 6)), ((2, 1.5), (4, 2.5)), ((4, 2.5), (2, 3.5))],     # thurisaz
    [((2, 0), (2, 6)), ((2, 0), (4, 1)), ((2, 1.5), (4, 2.5))],         # ansuz
    [((2, 0), (2, 6)), ((2, 0), (4, 1)), ((4, 1), (2, 3)), ((2, 3), (4, 6))],  # raidho
    [((4, 1), (1, 3.5)), ((1, 3.5), (4, 6))],                          # kenaz
    [((1, 0), (1, 6)), ((4, 0), (4, 6)), ((1, 3), (4, 3))],             # hagalaz
    [((2, 0), (2, 6))],                                                # isa
]

def tex_runes():
    s = SIZE
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    n = len(RUNES)
    cell = s // n
    pad = cell // 4
    for idx, strokes in enumerate(RUNES):
        ox = idx * cell + pad
        oy = s // 2 - (cell - 2 * pad) // 2
        cw, ch = cell - 2 * pad, cell - 2 * pad
        for (x0, y0), (x1, y1) in strokes:
            d.line([ox + x0 / 4.0 * cw, oy + y0 / 6.0 * ch,
                    ox + x1 / 4.0 * cw, oy + y1 / 6.0 * ch],
                   fill=(235, 240, 255, 255), width=max(3, cell // 16))
    # faint second row, offset, dimmer — usable as a longer strip
    for idx, strokes in enumerate(RUNES):
        ox = idx * cell + pad + cell // 2
        if ox + cell > s:
            break
        oy = s // 2 - (cell - 2 * pad) // 2
        cw, ch = cell - 2 * pad, cell - 2 * pad
        for (x0, y0), (x1, y1) in strokes:
            d.line([ox + x0 / 4.0 * cw, oy + y0 / 6.0 * ch,
                    ox + x1 / 4.0 * cw, oy + y1 / 6.0 * ch],
                   fill=(200, 210, 235, 140), width=max(2, cell // 20))
    img.save(os.path.join(TEX_DIR, "runes_alpha.png"))

def tex_frozeneath():
    s = SIZE
    soil = fbm(s, 5, 5)
    detail = fbm(s, 20, 3)
    ice_field = fbm(s, 3, 4)
    ice = np.clip((ice_field - 0.58) * 6.0, 0.0, 1.0)
    ice = np.clip(ice + 0.3 * np.clip((fbm(s, 8, 3) - 0.55) * 5.0, 0, 1), 0, 1)
    height = 0.6 * soil + 0.25 * detail + 0.15 * ice_field
    base_r = (0.23 + 0.10 * (soil - 0.5) * 2.0) * 255.0
    base_g = (0.19 + 0.09 * (soil - 0.5) * 2.0) * 255.0
    base_b = (0.16 + 0.08 * (soil - 0.5) * 2.0) * 255.0
    sparkle = (detail > 0.93).astype(float) * ice
    r = base_r * (1 - ice) + (185.0 + 40.0 * sparkle) * ice
    g = base_g * (1 - ice) + (210.0 + 30.0 * sparkle) * ice
    b = base_b * (1 - ice) + (235.0 + 20.0 * sparkle) * ice
    save_rgb(os.path.join(TEX_DIR, "frozeneath_albedo.png"), np.stack([r, g, b], axis=-1))
    save_rgb(os.path.join(TEX_DIR, "frozeneath_normal.png"),
             height_to_normal(height + 0.2 * ice, strength=1.8))

# --------------------------------------------------------------------- driver
def main():
    manifest = []
    print("== SFX ==")
    for name, target_dur, fn in SFX_JOBS:
        sig = fn()
        path = os.path.join(AUDIO_DIR, name)
        actual_dur = write_wav(path, sig)
        size = os.path.getsize(path)
        assert size > 0, f"empty file: {path}"
        peak = float(np.max(np.abs(fade(peak_normalize(sig)))))
        manifest.append(("audio/" + name, size, f"{actual_dur:.2f}s (target {target_dur:.2f}s)",
                         f"peak {20*np.log10(max(peak,1e-9)):.1f} dBFS"))
        print(f"  {name}: {size} bytes, {actual_dur:.2f}s")

    print("== TEXTURES ==")
    for name, fn in [("stone", tex_stone), ("iron", tex_iron),
                     ("runes", tex_runes), ("frozeneath", tex_frozeneath)]:
        fn()
    for f in sorted(os.listdir(TEX_DIR)):
        path = os.path.join(TEX_DIR, f)
        size = os.path.getsize(path)
        assert size > 0, f"empty file: {path}"
        with Image.open(path) as im:
            dims = f"{im.size[0]}x{im.size[1]} {im.mode}"
        manifest.append(("textures/" + f, size, dims, ""))
        print(f"  {f}: {size} bytes, {dims}")

    total = sum(m[1] for m in manifest)
    print(f"\nTotal files: {len(manifest)}, total size: {total/1024/1024:.2f} MB")
    assert total < 200 * 1024 * 1024, "output exceeds 200MB budget"

    # final verification pass
    expected_audio = [j[0] for j in SFX_JOBS]
    expected_tex = ["stone_albedo.png", "stone_normal.png", "stone_roughness.png",
                    "iron_albedo.png", "iron_roughness.png", "runes_alpha.png",
                    "frozeneath_albedo.png", "frozeneath_normal.png"]
    for f in expected_audio:
        p = os.path.join(AUDIO_DIR, f)
        assert os.path.isfile(p) and os.path.getsize(p) > 0, f"MISSING: {p}"
    for f in expected_tex:
        p = os.path.join(TEX_DIR, f)
        assert os.path.isfile(p) and os.path.getsize(p) > 0, f"MISSING: {p}"
    print("All deliverables verified: 12 WAVs + 8 PNGs present and non-empty.")
    return manifest

if __name__ == "__main__":
    main()
